# Параметры бокового меню
MIN_WIDTH = 0
MAX_WIDTH = 200
DURATION_SIDE_MENU = 600
DURATION_MAXIMIZED = 400
OPEN_MENU_ICON = "../icons/side_menu.png"
HIDE_MENU_ICON = "../icons/back_menu.png"
START_PICTURE = "../icons/unn_logo_ru.png"

# Параметры задачи
DEFAULT_SAMPLING_RATE = "160000"
DEFAULT_SIGNAL_FREQ = "10000"
DEFAULT_BITS_COUNT = "50"
DEFAULT_BITS_PER_SECOND = "1000"
DEFAULT_TIME_DELAY = "20"
DEFAULT_SNR = "10"
DEFAULT_AVERAGE_COUNT = "500"
